is_debug: true

logging:
  log-level: info

listen:
  type: port
  bind_ip: 0.0.0.0
  port: 1234

mongodb:
  host: localhost
  port: 27017
  database: user-service
  collection: users

postgres:
  host: localhost
  port: 5460
  database: postgres
  username: postgres
  password: postgres
  conn_retry_attempts: 5
  conn_retry_delay: 5


